version: 0.2

# env:
#   secrets-manager:
#     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
#     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - REPOSITORY_URI=909695425273.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecrrepository-ws-webaverse-$AWS_DEFAULT_REGION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Logging in to Docker Hub...
      - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - docker build -t $REPOSITORY_URI:latest --build-arg pm2_secret_key=${PM2_SECRET_KEY} .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 909695425273.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"ECSContainer-'$SERVICE_NAME'-'$AWS_DEFAULT_REGION'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
