export const classes = [
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "backpack",
  "umbrella",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "dining table",
  "toilet",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
  "banner",
  "blanket",
  "bridge",
  "cardboard",
  "counter",
  "curtain",
  "door-stuff",
  "floor-wood",
  "flower",
  "fruit",
  "gravel",
  "house",
  "light",
  "mirror-stuff",
  "net",
  "pillow",
  "platform",
  "playingfield",
  "railroad",
  "river",
  "road",
  "roof",
  "sand",
  "sea",
  "shelf",
  "snow",
  "stairs",
  "tent",
  "towel",
  "wall-brick",
  "wall-stone",
  "wall-tile",
  "wall-wood",
  "water-other",
  "window-blind",
  "window-other",
  "tree-merged",
  "fence-merged",
  "ceiling-merged",
  "sky-other-merged",
  "cabinet-merged",
  "table-merged",
  "floor-other-merged",
  "pavement-merged",
  "mountain-merged",
  "grass-merged",
  "dirt-merged",
  "paper-merged",
  "food-other-merged",
  "building-other-merged",
  "rock-merged",
  "wall-other-merged",
  "rug-merged",
];
export const categories = {
  floor: [
    "floor-wood",
    "gravel",
    "playingfield",
    "railroad",
    "river",
    "road",
    "sand",
    "sea",
    "snow",
    "water-other",
    "floor-other-merged",
    "pavement-merged",
    "grass-merged",
    "dirt-merged",
    "rock-merged",
    "rug-merged",
  ],
  wall: [
    "curtain",
    "wall-brick",
    "wall-stone",
    "wall-tile",
    "wall-wood",
    "window-blind",
    "fence-merged",
    "wall-other-merged",
    "roof",
  ],
  ceiling: [
    "ceiling-merged",
  ],
  portal: [
    "bridge",
    "door-stuff",
    "house",
    "platform",
    "stairs",
    "window-other",
    "tree-merged",
    "building-other-merged",
    "tent",
  ],
  seat: [
    "bench",
    "chair",
    "couch",
    "bed",
    "dining table",
    "toilet",
    "counter",
    "table-merged",
  ],
  light: [
    "traffic light",
    "light",
  ],
  npc: [
    "person",
  ],
  mob: [
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
  ],
  vehicle: [
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "skis",
    "snowboard",
    "skateboard",
    "surfboard",
  ],
  furniture: [
    "potted plant",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "teddy bear",
    "hair drier",
    "toothbrush",
    "banner",
    "blanket",
    "pillow",
    "shelf",
  ],
  weapon: [
    "umbrella",
    "handbag",
    "suitcase",
    "frisbee",
    "sports ball",
    "kite",
    "baseball bat",
    "tennis racket",
    "fork",
    "knife",
    "spoon",
    "scissors",
  ],
  nature: [
    "flower",
    "tree-merged",
    "sky-other-merged",
    "mountain-merged",
    "grass-merged",
  ],
  food: [
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "fruit",
    "food-other-merged",
  ],
  wearable: [
    "backpack",
    "tie",
    "baseball glove",
    "towel",
  ],
};
export const categoryClassIndices = (() => {
  const categoryClassIndices = {};
  for (const category in categories) {
    categoryClassIndices[category] = categories[category].map(className => classes.indexOf(className));
  }
  return categoryClassIndices;
})();